name: Release New RUM Library Version

permissions:
  id-token: write # Required for OIDC
  contents: read

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm@latest
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test:unit
      - run: npm run test:integration
      - run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: '' # Clear setup-node default to allow OIDC Trusted Publishing
